### ISSUE TITLE
Load scripts from hidden folders

### ISSUE THREAD

**Issue by NomarCub** [mnowotnik/obsidian-user-plugins#3]
I get the following error on console now when I try to load scripts from a hidden folder.
For actually invalid paths, this should also notify the user properly, for example with a notice, not only through the console.

```
Failed to read user scripts folder: Folder ".obsidian/scripts" doesn't exist
addUserScriptsListSetting @ plugin:obsidian-user-plugins:1904
display @ plugin:obsidian-user-plugins:1887
eval @ plugin:obsidian-user-plugins:1918
(anonymous) @ app.js:1
```

**Comment by mnowotnik** [comment]
fixed in 760cfa9

**Comment by NomarCub** [comment]
For anyone reading this later, the fix was only the better error reporting. you still can't use hidden folders.

**Comment by mnowotnik** [comment]
@NomarCub I will look into this, but the basic Obsidian API doesn't allow storing and reading files from .obsidian

**Comment by NomarCub** [comment]
No worries. It's been a while, and I couldn't see clearly what has been done. I just commented to clarify, for myself and others.
